name: Backend CI

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black ruff pytest pytest-cov build

      - name: Check Python syntax
        run: python -m compileall .

      - name: Lint with Ruff
        run: ruff check . --exit-zero

      - name: Check formatting with Black
        run: black --check .

      - name: Run tests with Pytest and show coverage
        run: pytest --cov=.
